### ISSUE TITLE
What is the difference between Azureml and Brightics?

### ISSUE THREAD

**Issue by ggokka** [brightics/studio#140]
Azureml has a powerful graphic design tool of Machine Learning.
So what is the benefit of using Brightics instead of Azureml.

**Comment by JaebooJung** [comment]
Hi, ggokka. There are a lot of differences between brightics and azureml. I don't intend to talk about pros and cons but conceptually differences as far as I can tell. First of all, azure is targeted to deploying their cloud service so the data you want to analyze must be uploaded to the cloud storage. Brightics is installed on both laptop and server then you can use the local data and cloud(s3) also. It has some strengths in mini batches when the data is changed periodically because it reduces the ready time to start analytics model everytime. The processes of installation are thought to be the weakness but we simplify them and make it portable so you can use or distribute brightics with just one zip file and only repackaging brightics home will allow you to move all your data to somewhere. Moreover, brightics doesn't need to sign up so you can use it offline. Second, the concept of GUI for brightics is data driven. Brightics focuses on showing the data and parameters in the same screen  for the convenience of handling the analytic functions. When you manipulate some parameters of the functions, you can immediately see how the output is changed. Brightics is updated frequently to add more functions. It means Brightics is pluggable and customizable so the users can easily add functions they want through our toolkit. Finally, we support Apache Spark to control the massive data from brightics enterprise and seamless data connection to brightics studio for the purpose of using output data from native python to Spark without rewriting. Brightics is a steadily growing project, so please keep watching us :) For more details, please contact us via email brightics@samsung.com.
