### ISSUE TITLE
Enable multi-user access on brightics studio

### ISSUE THREAD

**Issue by SETIADEEPANSHU** [brightics/studio#360]
There are two features which seems missing in the source code-
1) How to enable Multi-user access
2) When one model  is running in one tab, running other model in another tab shows "process is in queue", Is it possible with the current code to avoid this and if yes, how to do it?
Please comment @power4454 @seungrojoo @jy55266 @jisujeong @iisejin @jinhwanhan

**Comment by JaebooJung** [comment]
First of all, Brightics Studio is targeted to a single-user and it doesn't support run multiple models concurrently. The main reason for this circumstance is that one user can run only one model. It is because we separate Brightics into opensource and enterprise versions. The features including multi-user you said is already supported in enterprise version.

**Comment by SETIADEEPANSHU** [comment]
Hi @shovsj @JaebooJung is there any trial access for the brightics studio complete package, so that I can decide based on all available functionality and my requirements whether I should buy or not?

**Comment by JaebooJung** [comment]
@SETIADEEPANSHU To discuss it further, please send us an email to brightics@samsung.com. Then we share that with stakeholders and you will get detailed information.
